### ISSUE TITLE
Review removal of port_XXXXEXT_IRQ related functions

### ISSUE THREAD

**Issue by foldedtoad** [foldedtoad/dwm3000#4]
in platform/port.c there are four function which appear not needed.

- port_DIsableEXT_IRQ
- port_EnableEXT_IRQ
- port_GetEXT_IRQStatus
- port_CheckEXT_IRQ

These functions were included in the original code from Decawave, which targeted the Nordic SDK build environment. This Nordic SDK support is not a complete operating system, but rather a minimalistic platform.  As such the SPI support within it does not provide serialization for SPI transactions...the app must provide serialization within its code base.  This is what the nRF52840 code for the DWM3000 did, within the above functions.

But Zephyr is a much more complete OS and as such provide serialization of SPI transactions within the Zephyr-provided code.  In other words,  the above functions are redundant and actually add to the overall code path for the SPI transactions.
See ./zephyr/drivers/spi/spi_context.h (circa line 54) and the usage of the `lock` and `sync` mutexes.

In the future, I will remove this functions, and any references, such as in deca_mutex.c.   This change will have a ripple effect into the deca_spi.c code also.

**Comment by krbvroc1** [comment]
Are you sure that these are unnecessary? My understanding, which could be wrong, is that you need to mask IRQ so that the DW3000 interrupt does not fire while you are in the middle of reading/writing the registers.

**Comment by foldedtoad** [comment]
resolved
