### ISSUE TITLE
ex_05b_ds_twr_resp always returns DWT_ERROR

### ISSUE THREAD

**Issue by higherkuo** [foldedtoad/dwm3000#5]
I'm testing `ex_05a_ds_twr_init` and `ex_05b_ds_twr_resp` with nRF52840DK. However, the 05b always returns DWT_ERROR. I'm using Ubuntu with zephyr 2.7. Any thoughts? Thanks!

**Comment by higherkuo** [comment]
dig deeper and I found the issue is my board cannot process fast enough, so it always times out. Changing `POLL_RX_TO_RESP_TX_DLY_UUS` resolves timeout issue. In addition, `ex_05a_ds_twr_init` needs to be changed accordingly.

**Comment by kaleymer** [comment]
Hi, it looks like I've seen multiple people with the same issue on the nRF52840 board which I am using as well. Would you mind sharing the values you used for `POLL_RX_TO_RESP_TX_DLY_UUS` to resolve timeout issues? Thank you!
