### ISSUE TITLE
Unable to read devid

### ISSUE THREAD

**Issue by pvharmo** [foldedtoad/dwm3000#6]
I've been trying to run the example 00 however, the devid reads 6fe50101. I've read DECA0302 once, but now it doesn't work anymore, and I can't figure out what changed. I use the nrf52833-DK which made me think I had to change some configurations and I tried different config_options, but none seems to change the result.

**Comment by foldedtoad** [comment]
This has something to do with the SPI3 configuration.  From logic analyzer traces, the DECA0302 device seems to be using Polarity(0) and Phase(1).   I am investigating this now.
